blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/florentbebin-gif/ser1-site-frontend/blob/main/README.md
    about: Consultez le README avant d'ouvrir une issue.
  - name: ğŸ¤ Contribuer
    url: https://github.com/florentbebin-gif/ser1-site-frontend/blob/main/CONTRIBUTING.md
    about: Consultez les guidelines de contribution.
